version: '3.7'

networks:
  default:
    external:
      name: whirlpool-net


services:

  whirlpool-urlfilter:
    container_name: whirlpool-urlfilter
    entrypoint: bash ./scripts/wait-for-it.sh
    environment:
      - PY_ENV=development
    build:
      context: ./
      dockerfile: Dockerfile
      target: whirlpool-urlfilter-dev
    restart: on-failure
